---
engines:
  csslint:
    enabled: true
  markdownlint:
    enabled: true
    checks:
      MD013:
        enabled: false  
  eslint:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
      - javascript
  fixme:
    enabled: true
ratings:
  paths:
  - "**.css"
  - "**.html"
  - "**.js"
  - "**.htaccess"
  - "**.txt"
  - "**.xml"
  - "css/"
  - "js/"
  - "index.html"
exclude_paths:
  - "assets/"
  - "process/"
